name: Build
on:
  push:
    tags:
      - 'v*.*.*'
# Todo test it and add proper version numbers
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      - uses: actions/upload-artifact@v2
        with:
          name: digiwf-deployment-proxy
          path: |
            spring-boot-apps/digiwf-deployment-proxy/digiwf-deployment-proxy
            spring-boot-apps/digiwf-deployment-proxy/digiwf-deployment-proxy-starter
            spring-boot-apps/digiwf-deployment-proxy/digiwf-deployment-proxy-example

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Publish
        run: npm run publish

  publish-docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: spring-boot-apps/digiwf-deployment-proxy/digiwf-deployment-proxy-example
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD  }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./spring-boot-apps/digiwf-deployment-proxy/digiwf-deployment-proxy-starter-example
          push: true
          tags: flowsquad/digiwf-deployment-proxy:latest
