name: Build
on:
  push:
    tags:
      - 'v*.*.*'
    branch:
      - "feat/build-pipelines"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      - uses: actions/upload-artifact@v3
        with:
          name: digiwf-deployment-proxy
          path: |
            spring-boot-apps/digiwf-deployment-proxy/digiwf-deployment-proxy
            spring-boot-apps/digiwf-deployment-proxy/digiwf-deployment-proxy-starter
            spring-boot-apps/digiwf-deployment-proxy/digiwf-deployment-proxy-example

  package-version:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get package version
        id: package_version
        uses: Saionaro/extract-package-version@v1.1.1

  publish-npm:
    runs-on: ubuntu-latest
    needs: package-version
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Publish
        run: npm run publish

# publish maven

  publish-dockerhub:
    runs-on: ubuntu-latest
    needs: package-version
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: spring-boot-apps/digiwf-deployment-proxy/digiwf-deployment-proxy-example
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD  }}
      # digiwf-deployment-proxy
      - name: Build and push digiwf-deployment-proxy
        uses: docker/build-push-action@v2
        with:
          context: ./spring-boot-apps/digiwf-deployment-proxy/digiwf-deployment-proxy-starter-example
          push: true
          # Note: Version in package.json and maven should be the same!
          tags: flowsquad/digiwf-deployment-proxy:latest,flowsquad/digiwf-deployment-proxy:${{ steps.package_version.outputs.version }}
      # miragon-process-ide-cli
      - name: Build and push miragon-process-ide-cli
        uses: docker/build-push-action@v2
        with:
          context: ./dist/apps/miragon-process-ide-cli
          push: true
          tags: flowsquad/miragon-process-ide-cli:latest,flowsquad/miragon-process-ide-cli:${{ steps.package_version.outputs.version }}
