name: Release-test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
#      - name: Setup NodeJS 16
#        uses: actions/setup-node@v3
#        with:
#          node-version: '16'
#      - name: Install dependencies
#        run: npm install
#      - name: Lint
#        run: npm run lint
#      - name: Test
#        run: npm run test
#      - name: Build
#        run: npm run build
#      # process-ide-cli
#      - uses: actions/upload-artifact@v3
#        with:
#          name: process-ide-cli
#          path: dist/apps/miragon-process-ide-cli
#      # digiwf-lib
#      - uses: actions/upload-artifact@v3
#        with:
#          name: digiwf-lib
#          path: dist/libs/digiwf-lib
#      - uses: actions/upload-artifact@v3
#        with:
#          name: spring-boot-apps
#          path: spring-boot-apps

  create-release-tag:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: Create tag
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "my_tag"
