name: Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      - uses: actions/upload-artifact@v3
        with:
          name: spring-boot-apps
          path: spring-boot-apps

  publish-npm:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set release_version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Publish
        run: npm run publish

  publish-maven:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set release_version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      # tbd

  publish-dockerhub:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set release_version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/download-artifact@v3
        with:
          name: spring-boot-apps
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKER_MIRAGON_USERNAME }}
         password: ${{ secrets.DOCKER_MIRAGON_PASSWORD  }}
      # digiwf-deployment-proxy
      - name: Build and push digiwf-deployment-proxy
        uses: docker/build-push-action@v2
        with:
          context: ./digiwf-deployment-proxy
          push: true
          tags: miragon/digiwf-deployment-proxy:${{ env.RELEASE_VERSION }}
      # miragon-process-ide-cli
      - name: Build and push miragon-process-ide-cli
        uses: docker/build-push-action@v2
        with:
          context: ./apps/miragon-process-ide-cli
          push: true
          tags: miragon/process-ide-cli:${{ env.RELEASE_VERSION }}
