name: Test digiwf-lib
on:
  push:
    branches-ignore: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout sources
          uses: actions/checkout@v3
        - name: Setup NodeJS 16
          uses: actions/setup-node@v3
          with:
            node-version: '16'
        - name: Install dependencies
          run: npm install
        - name: Lint
          run: npm run lint
        - name: Test
          run: npm run test
        - name: Build
          run: npm run build
        # process-ide-vscode
        - uses: actions/upload-artifact@v3
          with:
            name: process-ide-cli
            path: dist/apps/process-ide-console

  publish-process-ide-console:
    if: ${{ github.event.inputs.process-ide-console }}
    runs-on: ubuntu-latest
    needs:
      - build
      - create-release-tag
    steps:
      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/download-artifact@v3
        with:
          name: process-ide-cli
      - name: Prepare
        run: npm install && npm install -g vsce
      - name: Build vsix
        run: vsce package
      # tbd. publish vsce
      - uses: actions/upload-artifact@v3
        with:
          name: process-ide-console-0.0.1.vsix
          path: process-ide-console-0.0.1.vsix
